### ISSUE TITLE
Not able to install Splicejam in R 

### ISSUE THREAD

**Issue by Relindis2018** [jmw86069/jambio#2]
I get error messages when installing Splicejam. This error was unexpected because I successfully used Splicejam a month ago. However, a month later, I got error messages each time I wanted to load the package. In an attempt to solve the problem, I uninstalled  splicejam and tried reinstalling again, but keep getting error messages. I am using two platforms, one having R version 3.6 and the other having R version 4:

The following error was generated from version 4.0
Error: Failed to install 'splicejam' from GitHub:
  Failed to install 'jamba' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Bruker/AppData/Local/Temp/RtmpU38hNU/file2b684a8e33e6/jamba_0.0.55.900.tar.gz’ had non-zero exit status

For R version 3.6, the following version was generated:
make: *** [cpp11.o] Error 1
ERROR: compilation failed for package ‘tidyr’
* removing ‘/home/relindis/R/x86_64-redhat-linux-gnu-library/3.6/tidyr’
Error: Failed to install 'splicejam' from GitHub:
  (converted from warning) installation of package ‘tidyr’ had non-zero exit status

I really appreciate any help that can enable me successfully install and load splicejam.
Thank you

**Comment by jmw86069** [comment]
Thank you for posting the error information, and I apologize I did not get notification about it, so I just now saw the problem! Ack!

It looks like the `tidyr` package installation is causing a problem? Can you run a test to see if this is the source of the error?

```R
install.packages("tidyr")
```

If that succeeds, then try installing splicejam again... maybe with some luck it will work and resolve the problem. (We can hope.) If not, let me know and I'll keep an eye out for follow-up responses. Thank you!

**Comment by jmw86069** [comment]
Closing.
