### ISSUE TITLE
jamGeomean(x, na.rm = TRUE) cannot handle NaN

### ISSUE THREAD

**Issue by leonie-r** [jmw86069/jambio#3]
Hello,
testing the jamGeomean() function on a vector containing NaN, it returns NaN although _na.rm_ is set to _TRUE_. <br>
small example
```
x = c(-3, 5, -4, 0, 4, -1, -2, 3, 2, -5, NaN)
jamGeomean(x, na.rm = TRUE)
[1] NaN
```

**Comment by jmw86069** [comment]
Thank you for posting the issue, and nice catch!

I have updated `splicejam` to version `0.0.76.900` to resolve this issue. As you know, you can update with:
`remotes::install_github("jmw86069/splicejam")`

Let me know if you have follow-up issues with this function, or feedback about the output.

**Comment by jmw86069** [comment]
Oops did not mean to close issue just yet!

**Comment by leonie-r** [comment]
Nice! Thank you for your immediate help, it works!
