### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by SerenaDudek** [jmw86069/jambio#4]
Bad Gateway as of 2 PM March 16. 😢
<img width="383" alt="Screen Shot 2023-03-16 at 2 09 04 PM" src="https://user-images.githubusercontent.com/94937727/225712999-d6f5b160-f403-4181-8db8-bf3cacd4c494.png">

**Comment by jmw86069** [comment]
Thank you for posting, at this point I can reproduce the error. I’ll look into what might be happening server-side, then will reach out to VTC if needed.

There were a couple recent server updates, maybe the internal R-shiny server was not properly restarted following the updates. It will probably be Monday before I learn more.

**Comment by jmw86069** [comment]
Well would you look at that, it resolved itself! Haha. My favorite kind of fix.

It seems like one of the dependent servers went offline and needed a nudge to restart. I'm not sure if Dr. Farris did the nudge, or if the servers eventually nudged themselves during the recurring update process? Either way, thank you for noticing and reporting the outage! And let me know if you do not see the fix on your side.

**Comment by SerenaDudek** [comment]
Thanks for ‘fixing’ it!! LOL
Looks like it works on my end!

Serena

From: James Ward ***@***.***>
Reply-To: jmw86069/splicejam ***@***.***>
Date: Tuesday, March 21, 2023 at 10:33 AM
To: jmw86069/splicejam ***@***.***>
Cc: Serena Dudek ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [jmw86069/splicejam] Bad Gateway (Issue #4)


Well would you look at that, it resolved itself! Haha. My favorite kind of fix.

It seems like one of the dependent servers went offline and needed a nudge to restart. I'm not sure if Dr. Farris did the nudge, or if the servers eventually nudged themselves during the recurring update process? Either way, thank you for noticing and reporting the outage! And let me know if you do not see the fix on your side.

—
(jmw: Edited to remove some extraneous Email footer text.)
